BLOCK_MENU:=Block Devices
CAN_MENU:=CAN Support
CRYPTO_MENU:=Cryptographic API modules
FIREWIRE_MENU:=FireWire support
FS_MENU:=Filesystems
HWMON_MENU:=Hardware Monitoring Support
I2C_MENU:=I2C support
INPUT_MODULES_MENU:=Input modules
LEDS_MENU:=LED modules
LIB_MENU:=Libraries
NETWORK_DEVICES_MENU:=Network Devices
NETWORK_SUPPORT_MENU:=Network Support
NF_MENU:=Netfilter Extensions
OTHER_MENU:=Other modules
PCMCIA_MENU:=PCMCIA support
SOUND_MENU:=Sound Support
SPI_MENU:=SPI Support
USB_MENU:=USB Support
VIDEO_MENU:=Video Support
VIRTUAL_MENU:=Virtualization Support
W1_MENU:=W1 support
WIRELESS_MENU:=Wireless Drivers
WPAN_MENU:=Wireless Drivers
