#
# Copyright (C) 2022 Keenetic Limited
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=ndmfw
PKG_VERSION:=1

include $(INCLUDE_DIR)/host-build.mk

define Host/Compile
endef

define Host/Install
endef

$(eval $(call HostBuild))
